#!/usr/bin/env bash

# Install oh-my-zsh
curl -L http://install.ohmyz.sh | sh


# Set zsh as default shell
chsh -s /bin/zsh

# Get rid of default .zshrc file
rm $HOME/.zshrc

# Create aliases in home directory
ln -sf $HOME/src/machine-config/gitconfig $HOME/.gitconfig
ln -sf $HOME/src/machine-config/tmux.conf $HOME/.tmux.conf
ln -sf $HOME/src/machine-config/vim $HOME/.vim
ln -sf $HOME/src/machine-config/vimrc $HOME/.vimrc
ln -sf $HOME/src/machine-config/zshrc $HOME/.zshrc

# Install and setup vundle for vim Plugins
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

